// Code generated by mockery v2.47.0. DO NOT EDIT.

package mocks

import (
	context "context"
	dtos "library-api/dtos"

	mock "github.com/stretchr/testify/mock"
)

// BorrowService is an autogenerated mock type for the BorrowService type
type BorrowService struct {
	mock.Mock
}

// PostNewBorrowService provides a mock function with given fields: _a0, _a1, _a2
func (_m *BorrowService) PostNewBorrowService(_a0 context.Context, _a1 dtos.RequestBorrowBook, _a2 int64) (*dtos.ResponseBorrow, error) {
	ret := _m.Called(_a0, _a1, _a2)

	if len(ret) == 0 {
		panic("no return value specified for PostNewBorrowService")
	}

	var r0 *dtos.ResponseBorrow
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, dtos.RequestBorrowBook, int64) (*dtos.ResponseBorrow, error)); ok {
		return rf(_a0, _a1, _a2)
	}
	if rf, ok := ret.Get(0).(func(context.Context, dtos.RequestBorrowBook, int64) *dtos.ResponseBorrow); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dtos.ResponseBorrow)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, dtos.RequestBorrowBook, int64) error); ok {
		r1 = rf(_a0, _a1, _a2)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PostReturnBookService provides a mock function with given fields: _a0, _a1, _a2
func (_m *BorrowService) PostReturnBookService(_a0 context.Context, _a1 dtos.RequestReturnBook, _a2 int64) (*dtos.ResponseBorrow, error) {
	ret := _m.Called(_a0, _a1, _a2)

	if len(ret) == 0 {
		panic("no return value specified for PostReturnBookService")
	}

	var r0 *dtos.ResponseBorrow
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, dtos.RequestReturnBook, int64) (*dtos.ResponseBorrow, error)); ok {
		return rf(_a0, _a1, _a2)
	}
	if rf, ok := ret.Get(0).(func(context.Context, dtos.RequestReturnBook, int64) *dtos.ResponseBorrow); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dtos.ResponseBorrow)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, dtos.RequestReturnBook, int64) error); ok {
		r1 = rf(_a0, _a1, _a2)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewBorrowService creates a new instance of BorrowService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewBorrowService(t interface {
	mock.TestingT
	Cleanup(func())
}) *BorrowService {
	mock := &BorrowService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
