// Code generated by mockery v2.47.0. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// TransactionRepository is an autogenerated mock type for the TransactionRepository type
type TransactionRepository struct {
	mock.Mock
}

// Atomic provides a mock function with given fields: c, fn
func (_m *TransactionRepository) Atomic(c context.Context, fn func(context.Context) (any, error)) (any, error) {
	ret := _m.Called(c, fn)

	if len(ret) == 0 {
		panic("no return value specified for Atomic")
	}

	var r0 any
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, func(context.Context) (any, error)) (any, error)); ok {
		return rf(c, fn)
	}
	if rf, ok := ret.Get(0).(func(context.Context, func(context.Context) (any, error)) any); ok {
		r0 = rf(c, fn)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(any)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, func(context.Context) (any, error)) error); ok {
		r1 = rf(c, fn)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewTransactionRepository creates a new instance of TransactionRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTransactionRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *TransactionRepository {
	mock := &TransactionRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
